// apps/studio/app/components/contribution-panel.tsx
"use client";

import { useMemo, useState } from "react";
import {
  MapPinIcon,
  PencilIcon,
  PlusIcon,
  Trash2Icon,
  ExternalLinkIcon,
  CheckIcon,
  CopyIcon,
} from "lucide-react";
import { Button } from "@repo/ui/components/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@repo/ui/components/dialog";
import { ScrollArea } from "@repo/ui/components/scroll-area";
import { Separator } from "@repo/ui/components/separator";
import { Input } from "@repo/ui/components/input";
import { Label } from "@repo/ui/components/label";
import { toast } from "sonner";
import { useContribution } from "../contexts/contribution-context";
import { generatePRTitle, generatePRBody } from "../lib/pr-generator";
import type { StationChange } from "../types/contribution";
import { cn } from "@repo/ui/lib/utils";

interface ContributionPanelProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const GITHUB_REPO_OWNER = "r4ultv";
const GITHUB_REPO_NAME = "rail-radar";

function formatChangeDetails(change: StationChange): string {
  const { type, details } = change;

  if (type === "created") {
    if (details.newGeo) {
      return `Created at (${details.newGeo.lat.toFixed(4)}, ${details.newGeo.lng.toFixed(4)})`;
    }
    return "Created";
  }

  if (type === "deleted") {
    return "Deleted";
  }

  const updates: string[] = [];
  if (details.coordinatesUpdated && details.newGeo) {
    updates.push(`Moved to (${details.newGeo.lat.toFixed(4)}, ${details.newGeo.lng.toFixed(4)})`);
  }
  if (details.nameChanged) {
    updates.push(`Renamed from "${details.previousName}"`);
  }

  return updates.join(", ");
}

function ChangeIcon({ type }: { type: StationChange["type"] }) {
  const iconClass = "size-4";
  switch (type) {
    case "created":
      return <PlusIcon className={cn(iconClass, "text-green-500")} />;
    case "updated":
      return <PencilIcon className={cn(iconClass, "text-blue-500")} />;
    case "deleted":
      return <Trash2Icon className={cn(iconClass, "text-red-500")} />;
  }
}

export function ContributionPanel({ open, onOpenChange }: ContributionPanelProps) {
  const { changes, stats, clearSession, isSessionActive } = useContribution();
  const [titleCopied, setTitleCopied] = useState(false);
  const [bodyCopied, setBodyCopied] = useState(false);

  const title = useMemo(() => {
    if (!stats) return "";
    return generatePRTitle(stats);
  }, [stats]);

  const body = useMemo(() => {
    if (!stats) return "";
    return generatePRBody(changes, stats);
  }, [changes, stats]);

  const handleCopyTitle = async () => {
    try {
      await navigator.clipboard.writeText(title);
      setTitleCopied(true);
      toast.success("Title copied to clipboard");
      setTimeout(() => setTitleCopied(false), 2000);
    } catch {
      toast.error("Failed to copy title");
    }
  };

  const handleCopyBody = async () => {
    try {
      await navigator.clipboard.writeText(body);
      setBodyCopied(true);
      toast.success("Body copied to clipboard");
      setTimeout(() => setBodyCopied(false), 2000);
    } catch {
      toast.error("Failed to copy body");
    }
  };

  const handleOpenInGitHub = () => {
    const params = new URLSearchParams({
      quick_pull: "1",
      title,
      body,
    });
    const url = `https://github.com/${GITHUB_REPO_OWNER}/${GITHUB_REPO_NAME}/compare/main...HEAD?${params.toString()}`;
    window.open(url, "_blank");
  };

  const handleClearSession = () => {
    clearSession();
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="flex max-h-[85vh] flex-col sm:max-w-xl">
        <DialogHeader>
          <DialogTitle>Contribution Session</DialogTitle>
          <DialogDescription>Review your changes</DialogDescription>
        </DialogHeader>

        <div className="min-h-0 flex-1 space-y-4">
          {stats && (
            <>
              <div className="grid grid-cols-3 gap-4 text-sm">
                <div className="space-y-1">
                  <div className="text-muted-foreground">Changes</div>
                  <div className="text-2xl font-semibold">{stats.changesCount}</div>
                </div>
                <div className="space-y-1">
                  <div className="text-muted-foreground">Coords Moved</div>
                  <div className="text-2xl font-semibold">{stats.coordinatesUpdated}</div>
                </div>
                <div className="space-y-1">
                  <div className="text-muted-foreground">Renamed</div>
                  <div className="text-2xl font-semibold">{stats.stationsRenamed}</div>
                </div>
              </div>

              <Separator />
            </>
          )}

          <ScrollArea className="max-h-48">
            {changes.length === 0 ? (
              <div className="py-8 text-center text-sm text-muted-foreground">
                <MapPinIcon className="mx-auto mb-2 size-8 opacity-50" />
                <p>No changes yet</p>
                <p className="mt-1">Start editing stations to track your contributions.</p>
              </div>
            ) : (
              <div className="space-y-2 pr-4">
                {changes.map((change) => (
                  <div
                    key={change.id}
                    className="flex items-start gap-3 rounded-md border border-border bg-card p-3"
                  >
                    <ChangeIcon type={change.type} />
                    <div className="min-w-0 flex-1">
                      <div className="truncate font-medium">{change.stationName}</div>
                      <div className="text-xs text-muted-foreground">
                        {formatChangeDetails(change)}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </ScrollArea>

          {isSessionActive && (
            <>
              <Separator />

              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <Label htmlFor="pr-title">PR Title</Label>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={handleCopyTitle}
                    className="h-7 gap-1.5 text-xs"
                  >
                    {titleCopied ? (
                      <>
                        <CheckIcon className="size-3" />
                        Copied
                      </>
                    ) : (
                      <>
                        <CopyIcon className="size-3" />
                        Copy
                      </>
                    )}
                  </Button>
                </div>
                <Input id="pr-title" value={title} readOnly className="font-mono text-sm" />
              </div>

              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <Label htmlFor="pr-body">PR Description</Label>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={handleCopyBody}
                    className="h-7 gap-1.5 text-xs"
                  >
                    {bodyCopied ? (
                      <>
                        <CheckIcon className="size-3" />
                        Copied
                      </>
                    ) : (
                      <>
                        <CopyIcon className="size-3" />
                        Copy
                      </>
                    )}
                  </Button>
                </div>
                <ScrollArea className="max-h-40 rounded-md border border-input bg-input/30">
                  <pre id="pr-body" className="whitespace-pre-wrap p-3 font-mono text-xs">
                    {body}
                  </pre>
                </ScrollArea>
              </div>
            </>
          )}
        </div>

        <DialogFooter className="gap-2">
          <Button variant="outline" onClick={handleClearSession}>
            Clear Session
          </Button>
          <Button onClick={handleOpenInGitHub} disabled={!isSessionActive}>
            <ExternalLinkIcon className="size-4" />
            Open in GitHub
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// apps/studio/src/lib/components/ContributionPanel.svelte
<script lang="ts">
  import { CheckIcon, CopyIcon, ExternalLinkIcon, MapPinIcon } from "@lucide/svelte";
  import { Badge } from "$lib/components/ui/badge";
  import { Button } from "$lib/components/ui/button";
  import * as Dialog from "$lib/components/ui/dialog";
  import { Input } from "$lib/components/ui/input";
  import { Label } from "$lib/components/ui/label";
  import { ScrollArea } from "$lib/components/ui/scroll-area";
  import { Separator } from "$lib/components/ui/separator";
  import { generatePRBody, generatePRTitle } from "$lib/pr-generator";
  import { contributionStore } from "$lib/stores/contribution";
  import type { StationChange } from "$lib/types/contribution";

  let {
    open,
    onOpenChange,
  }: {
    open: boolean;
    onOpenChange: (open: boolean) => void;
  } = $props();

  let copied = $state<"title" | "body" | null>(null);

  const changesStore = contributionStore.changes;
  const statsStore = contributionStore.stats;
  const isSessionActiveStore = contributionStore.isSessionActive;
  const changes = $derived($changesStore);
  const stats = $derived($statsStore);
  const isSessionActive = $derived($isSessionActiveStore);
  const title = $derived(stats ? generatePRTitle(stats) : "");
  const body = $derived(stats ? generatePRBody(changes, stats) : "");

  function formatChangeDetails(change: StationChange): string {
    if (change.type === "created") {
      return change.details.newGeo
        ? `Created at (${change.details.newGeo.lat.toFixed(4)}, ${change.details.newGeo.lng.toFixed(4)})`
        : "Created";
    }
    if (change.type === "deleted") return "Deleted";

    const updates: string[] = [];
    if (change.details.coordinatesUpdated && change.details.newGeo) {
      updates.push(
        `Moved to (${change.details.newGeo.lat.toFixed(4)}, ${change.details.newGeo.lng.toFixed(4)})`,
      );
    }
    if (change.details.nameChanged) updates.push(`Renamed from "${change.details.previousName}"`);
    if (change.details.typeChanged) updates.push(`Type changed to ${change.details.newType}`);
    if (change.details.importanceChanged) {
      updates.push(`Importance changed to ${change.details.newImportance}`);
    }
    return updates.join(", ") || "Updated";
  }

  async function copyText(kind: "title" | "body", value: string) {
    await navigator.clipboard.writeText(value);
    copied = kind;
    window.setTimeout(() => {
      if (copied === kind) copied = null;
    }, 1600);
  }

  function openGitHub() {
    const params = new URLSearchParams({ quick_pull: "1", title, body });
    window.open(`https://github.com/r4ultv/rail-radar/compare/main...HEAD?${params.toString()}`, "_blank");
  }

  function clearSession() {
    contributionStore.clearSession();
    onOpenChange(false);
  }
</script>

<Dialog.Root {open} onOpenChange={onOpenChange}>
  <Dialog.Content class="flex max-h-[85vh] flex-col sm:max-w-xl">
    <Dialog.Header>
      <Dialog.Title>Contribution Session</Dialog.Title>
      <Dialog.Description>Review your changes</Dialog.Description>
    </Dialog.Header>

    <div class="min-h-0 flex-1 space-y-4 overflow-hidden">
      {#if stats}
        <div class="grid grid-cols-3 gap-4 text-sm">
          <div>
            <div class="text-muted-foreground">Changes</div>
            <div class="text-2xl font-semibold">{stats.changesCount}</div>
          </div>
          <div>
            <div class="text-muted-foreground">Coords Moved</div>
            <div class="text-2xl font-semibold">{stats.coordinatesUpdated}</div>
          </div>
          <div>
            <div class="text-muted-foreground">Renamed</div>
            <div class="text-2xl font-semibold">{stats.stationsRenamed}</div>
          </div>
        </div>
        <Separator />
      {/if}

      <ScrollArea class="max-h-48">
        {#if changes.length === 0}
          <div class="py-8 text-center text-sm text-muted-foreground">
            <MapPinIcon class="mx-auto mb-2 size-8 opacity-50" />
            <p>No changes yet</p>
            <p class="mt-1">Start editing stations to track your contributions.</p>
          </div>
        {:else}
          <div class="space-y-2 pr-4">
            {#each changes as change (change.id)}
              <div class="rounded-md border border-border bg-muted/30 p-3">
                <div class="flex items-center gap-2">
                  <Badge variant={change.type === "deleted" ? "destructive" : "secondary"}>{change.type}</Badge>
                  <div class="min-w-0 truncate font-medium">{change.stationName}</div>
                </div>
                <div class="mt-1 text-xs text-muted-foreground">{formatChangeDetails(change)}</div>
              </div>
            {/each}
          </div>
        {/if}
      </ScrollArea>

      {#if isSessionActive}
        <Separator />

        <div class="space-y-2">
          <div class="flex items-center justify-between">
            <Label for="pr-title">PR Title</Label>
            <Button variant="ghost" size="sm" onclick={() => copyText("title", title)}>
              {#if copied === "title"}<CheckIcon class="size-3" /> Copied{:else}<CopyIcon class="size-3" /> Copy{/if}
            </Button>
          </div>
          <Input id="pr-title" value={title} readonly class="font-mono text-sm" />
        </div>

        <div class="space-y-2">
          <div class="flex items-center justify-between">
            <Label for="pr-body">PR Description</Label>
            <Button variant="ghost" size="sm" onclick={() => copyText("body", body)}>
              {#if copied === "body"}<CheckIcon class="size-3" /> Copied{:else}<CopyIcon class="size-3" /> Copy{/if}
            </Button>
          </div>
          <ScrollArea class="h-48 rounded-md border border-border bg-muted/30">
            <pre id="pr-body" class="whitespace-pre-wrap p-3 font-mono text-xs">{body}</pre>
          </ScrollArea>
        </div>
      {/if}
    </div>

    <Dialog.Footer>
      <Button variant="outline" onclick={clearSession}>Clear Session</Button>
      <Button disabled={!isSessionActive} onclick={openGitHub}>
        <ExternalLinkIcon class="size-4" />
        Open in GitHub
      </Button>
    </Dialog.Footer>
  </Dialog.Content>
</Dialog.Root>
