// apps/studio/app/components/station-sidebar.tsx
"use client";

import { useMemo, useState } from "react";
import {
  CopyIcon,
  ListIcon,
  MapPinOffIcon,
  PlusIcon,
  SearchIcon,
  SquareMIcon,
  TramFrontIcon,
  XIcon,
} from "lucide-react";
import { Button } from "@repo/ui/components/button";
import { Input } from "@repo/ui/components/input";
import { ScrollArea } from "@repo/ui/components/scroll-area";
import { Tabs, TabsList, TabsTrigger } from "@repo/ui/components/tabs";
import type { Station } from "@repo/data";
import { cn } from "@repo/ui/lib/utils";
import type { ChangeType } from "../types/contribution";

type FilterType = "all" | "missing" | "metro" | "light" | "duplicate";

interface StationSidebarProps {
  stations: Station[];
  selectedStationId: string | null;
  isAddingStation: boolean;
  changedStationIds?: Map<string, ChangeType>;
  onSelectStation: (id: string) => void;
  onAddStationClick: () => void;
  contributionBanner?: React.ReactNode;
}

function getChangeIndicatorColor(changeType: ChangeType | undefined): string {
  switch (changeType) {
    case "created":
      return "bg-green-500";
    case "updated":
      return "bg-blue-500";
    case "deleted":
      return "bg-red-500";
    default:
      return "";
  }
}

export function StationSidebar({
  stations,
  selectedStationId,
  isAddingStation,
  changedStationIds,
  onSelectStation,
  onAddStationClick,
  contributionBanner,
}: StationSidebarProps) {
  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState<FilterType>("all");

  const filteredStations = useMemo(() => {
    let result = stations;

    // Apply search filter
    if (search.trim()) {
      const lowerSearch = search.toLowerCase();
      result = result.filter((s) => s.name.toLowerCase().includes(lowerSearch));
    }

    // Apply type filter
    if (filter === "missing") {
      result = result.filter((s) => !s.geo);
    } else if (filter === "metro") {
      result = result.filter((s) => s.type === "metro");
    } else if (filter === "light") {
      result = result.filter((s) => s.type === "light");
    } else if (filter === "duplicate") {
      // Find stations with duplicate names
      const nameCounts = new Map<string, number>();
      stations.forEach((s) => {
        const name = s.name.toLowerCase();
        nameCounts.set(name, (nameCounts.get(name) ?? 0) + 1);
      });

      // Find stations with duplicate coordinates
      const geoCounts = new Map<string, number>();
      stations.forEach((s) => {
        if (s.geo) {
          const key = `${s.geo.lat},${s.geo.lng}`;
          geoCounts.set(key, (geoCounts.get(key) ?? 0) + 1);
        }
      });

      result = result.filter((s) => {
        const nameIsDuplicate = (nameCounts.get(s.name.toLowerCase()) ?? 0) > 1;
        const geoIsDuplicate =
          s.geo && (geoCounts.get(`${s.geo.lat},${s.geo.lng}`) ?? 0) > 1;
        return nameIsDuplicate || geoIsDuplicate;
      });
    }

    return result;
  }, [stations, search, filter]);

  const renderStationItem = (station: Station) => {
    const changeType = changedStationIds?.get(station.id);
    const changeIndicatorColor = getChangeIndicatorColor(changeType);
    const hasGeo = !!station.geo;

    return (
      <button
        key={station.id}
        onClick={() => onSelectStation(station.id)}
        className={cn(
          "flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm transition-colors hover:bg-muted",
          selectedStationId === station.id && "bg-muted text-foreground",
        )}
      >
        <span className="relative flex items-center justify-center">
          <span
            className={cn(
              "size-2 shrink-0 rounded-full",
              hasGeo ? "bg-green-500" : "bg-muted-foreground/50",
            )}
          />
          {changeType && (
            <span
              className={cn(
                "absolute -right-0.5 -top-0.5 size-1.5 rounded-full ring-2 ring-card",
                changeIndicatorColor,
              )}
            />
          )}
        </span>
        <span className="truncate">{station.name}</span>
        {station.type === "metro" && (
          <SquareMIcon className="size-3 shrink-0 text-muted-foreground" />
        )}
        {station.type === "light" && (
          <TramFrontIcon className="size-3 shrink-0 text-muted-foreground" />
        )}
      </button>
    );
  };

  return (
    <div className="flex h-full w-80 shrink-0 flex-col overflow-hidden border-r border-border bg-card">
      <div className="flex shrink-0 flex-col gap-3 p-4">
        {contributionBanner}
        <div className="relative">
          <SearchIcon className="absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            placeholder="Search stations..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className={cn("pl-9", search && "pr-9")}
          />
          {search && (
            <button
              onClick={() => setSearch("")}
              className="absolute right-2.5 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
            >
              <XIcon className="size-4" />
            </button>
          )}
        </div>
        <Button
          variant={isAddingStation ? "secondary" : "outline"}
          onClick={onAddStationClick}
          className="w-full"
        >
          <PlusIcon className="size-4" />
          Add Station
        </Button>
        <Tabs
          value={filter}
          onValueChange={(value) => setFilter(value as FilterType)}
        >
          <TabsList className="w-full">
            <TabsTrigger value="all">
              <ListIcon className="size-3" />
              {filter === "all" && "All"}
            </TabsTrigger>
            <TabsTrigger value="missing">
              <MapPinOffIcon className="size-3" />
              {filter === "missing" && "Missing"}
            </TabsTrigger>
            <TabsTrigger value="metro">
              <SquareMIcon className="size-3" />
              {filter === "metro" && "Metro"}
            </TabsTrigger>
            <TabsTrigger value="light">
              <TramFrontIcon className="size-3" />
              {filter === "light" && "Light"}
            </TabsTrigger>
            <TabsTrigger value="duplicate">
              <CopyIcon className="size-3" />
              {filter === "duplicate" && "Duplicate"}
            </TabsTrigger>
          </TabsList>
        </Tabs>
      </div>

      <div className="shrink-0 px-4 pb-2 text-xs font-medium text-muted-foreground">
        {filteredStations.length} station
        {filteredStations.length !== 1 ? "s" : ""}
      </div>

      <ScrollArea className="min-h-0 flex-1 [&_[data-slot=scroll-area-viewport]]:h-full">
        <div className="flex flex-col gap-0.5 px-2 pb-4">
          {filteredStations.map((station) => renderStationItem(station))}
        </div>
      </ScrollArea>
    </div>
  );
}

// apps/studio/src/lib/components/StationSidebar.svelte
<script lang="ts">
    import type { Station } from "@repo/data";
    import {
        CopyIcon,
        ListIcon,
        SearchIcon,
        SquareMIcon,
        TramFrontIcon,
        XIcon,
    } from "@lucide/svelte";
    import { Button } from "$lib/components/ui/button";
    import { Input } from "$lib/components/ui/input";
    import { ScrollArea } from "$lib/components/ui/scroll-area";
    import * as Tabs from "$lib/components/ui/tabs";
    import type { ChangeType } from "$lib/types/contribution";
    import { cn } from "$lib/utils";

    type FilterType = "all" | "metro" | "light" | "duplicate";
    const ROW_HEIGHT = 36;
    const OVERSCAN = 12;

    let {
        stations,
        selectedStationId,
        changedStationIds,
        onSelectStation,
    }: {
        stations: Station[];
        selectedStationId: string | null;
        changedStationIds: Map<string, ChangeType>;
        onSelectStation: (id: string) => void;
    } = $props();

    let search = $state("");
    let filter = $state<FilterType>("all");
    let scrollTop = $state(0);
    let viewportHeight = $state(0);
    let scrollContainer = $state<HTMLElement | null>(null);
    let lastFilterKey = $state("");

    let filteredStations = $derived.by(() => {
        let result = stations;
        if (search.trim()) {
            const lower = search.toLowerCase();
            result = result.filter((station) =>
                station.name.toLowerCase().includes(lower),
            );
        }

        if (filter === "metro")
            result = result.filter((station) => station.type === "metro");
        if (filter === "light")
            result = result.filter((station) => station.type === "light");
        if (filter === "duplicate") {
            const nameCounts = new Map<string, number>();
            const geoCounts = new Map<string, number>();
            for (const station of stations) {
                const name = station.name.toLowerCase();
                nameCounts.set(name, (nameCounts.get(name) ?? 0) + 1);
                if (station.geo) {
                    const key = `${station.geo.lat},${station.geo.lng}`;
                    geoCounts.set(key, (geoCounts.get(key) ?? 0) + 1);
                }
            }

            result = result.filter((station) => {
                const duplicateName =
                    (nameCounts.get(station.name.toLowerCase()) ?? 0) > 1;
                const duplicateGeo =
                    station.geo &&
                    (geoCounts.get(`${station.geo.lat},${station.geo.lng}`) ??
                        0) > 1;
                return duplicateName || duplicateGeo;
            });
        }

        return result;
    });
    const totalHeight = $derived(filteredStations.length * ROW_HEIGHT);
    const startIndex = $derived(
        Math.max(0, Math.floor(scrollTop / ROW_HEIGHT) - OVERSCAN),
    );
    const visibleCount = $derived(
        Math.ceil(viewportHeight / ROW_HEIGHT) + OVERSCAN * 2,
    );
    const visibleStations = $derived(
        filteredStations.slice(startIndex, startIndex + visibleCount),
    );
    const offsetY = $derived(startIndex * ROW_HEIGHT);

    $effect(() => {
        const filterKey = `${search}\u0000${filter}`;
        if (filterKey === lastFilterKey) return;
        lastFilterKey = filterKey;
        scrollTop = 0;
        if (scrollContainer) scrollContainer.scrollTop = 0;
    });

    $effect(() => {
        const viewport = scrollContainer;
        if (!viewport) return;

        const syncScrollMetrics = () => {
            scrollTop = viewport.scrollTop;
            viewportHeight = viewport.clientHeight;
        };
        const resizeObserver = new ResizeObserver(syncScrollMetrics);

        syncScrollMetrics();
        resizeObserver.observe(viewport);
        viewport.addEventListener("scroll", syncScrollMetrics, {
            passive: true,
        });

        return () => {
            resizeObserver.disconnect();
            viewport.removeEventListener("scroll", syncScrollMetrics);
        };
    });

    function changeClass(changeType: ChangeType | undefined): string {
        if (changeType === "created") return "bg-green-500";
        if (changeType === "updated") return "bg-blue-500";
        if (changeType === "deleted") return "bg-red-500";
        return "";
    }
</script>

<aside
    class="flex h-full w-72 shrink-0 flex-col overflow-hidden border-r border-sidebar-border bg-sidebar text-sidebar-foreground max-lg:w-[18rem] max-md:hidden"
>
    <div
        class="flex shrink-0 flex-col gap-3 border-b border-sidebar-border p-3"
    >
        <div class="flex items-baseline justify-between">
            <h2
                class="font-mono text-[11px] uppercase tracking-wider text-muted-foreground"
            >
                Stations
            </h2>
            <span
                class="font-mono text-[11px] tabular-nums text-muted-foreground"
            >
                {filteredStations.length}
                <span class="text-muted-foreground/60">
                    / {stations.length}</span
                >
            </span>
        </div>
        <div class="relative">
            <SearchIcon
                class="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"
            />
            <Input
                class="w-full pl-9"
                placeholder="Search stations..."
                bind:value={search}
            />
            {#if search}
                <Button
                    variant="ghost"
                    size="icon-xs"
                    class="absolute right-2 top-1/2 -translate-y-1/2"
                    onclick={() => (search = "")}
                >
                    <XIcon class="size-3" />
                </Button>
            {/if}
        </div>

        <Tabs.Root bind:value={filter} class="gap-0">
            <Tabs.List class="flex h-8 w-full">
                <Tabs.Trigger value="all" title="All stations" class="gap-1.5">
                    <ListIcon class="size-3" />
                    {#if filter === "all"}<span class="text-xs">All</span>{/if}
                </Tabs.Trigger>
                <Tabs.Trigger value="metro" title="Metro" class="gap-1.5">
                    <SquareMIcon class="size-3" />
                    {#if filter === "metro"}<span class="text-xs">Metro</span>{/if}
                </Tabs.Trigger>
                <Tabs.Trigger value="light" title="Light rail" class="gap-1.5">
                    <TramFrontIcon class="size-3" />
                    {#if filter === "light"}<span class="text-xs">Light</span>{/if}
                </Tabs.Trigger>
                <Tabs.Trigger value="duplicate" title="Duplicates" class="gap-1.5">
                    <CopyIcon class="size-3" />
                    {#if filter === "duplicate"}<span class="text-xs">Duplicates</span>{/if}
                </Tabs.Trigger>
            </Tabs.List>
        </Tabs.Root>
    </div>

    <ScrollArea bind:viewportRef={scrollContainer} class="min-h-0 flex-1">
        {#if filteredStations.length === 0}
            <div class="px-4 py-8 text-center text-xs text-muted-foreground">
                No stations match your filters.
            </div>
        {:else}
            <div class="relative" style:height={`${totalHeight}px`}>
                <div
                    class="absolute inset-x-0 top-0"
                    style:transform={`translateY(${offsetY}px)`}
                >
                    {#each visibleStations as station (station.id)}
                        {@const changeType = changedStationIds.get(station.id)}
                        <Button
                            variant="ghost"
                            size="sm"
                            class={cn(
                                "h-9 w-full justify-start rounded-none border-l-2 border-l-transparent px-3 text-left text-sm text-muted-foreground hover:bg-sidebar-accent hover:text-foreground",
                                selectedStationId === station.id &&
                                    "bg-muted text-foreground",
                                selectedStationId === station.id &&
                                    "border-l-primary",
                            )}
                            onclick={() => onSelectStation(station.id)}
                        >
                            <span
                                class="relative flex items-center justify-center"
                            >
                                <span
                                    class="block size-2 rounded-full bg-green-500"
                                ></span>
                                {#if changeType}
                                    <span
                                        class={`absolute -right-0.5 -top-0.5 size-1.5 rounded-full ring-2 ring-card ${changeClass(changeType)}`}
                                    ></span>
                                {/if}
                            </span>
                            <span class="min-w-0 flex-1 truncate"
                                >{station.name}</span
                            >
                            {#if station.type === "metro"}<SquareMIcon
                                    class="size-3 text-muted-foreground"
                                />{/if}
                            {#if station.type === "light"}<TramFrontIcon
                                    class="size-3 text-muted-foreground"
                                />{/if}
                        </Button>
                    {/each}
                </div>
            </div>
        {/if}
    </ScrollArea>
</aside>
