// apps/studio/app/components/station-edit-panel.tsx
"use client";

import { useEffect, useState } from "react";
import {
  BookOpenIcon,
  ChevronDownIcon,
  MapIcon,
  RadioTowerIcon,
  SaveIcon,
  Trash2Icon,
  XIcon,
} from "lucide-react";
import { Button, buttonVariants } from "@repo/ui/components/button";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@repo/ui/components/collapsible";
import { Input } from "@repo/ui/components/input";
import { Label } from "@repo/ui/components/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@repo/ui/components/select";
import type { Station } from "@repo/data";

import { cn } from "@repo/ui/lib/utils";
import { WikipediaInfo } from "./wikipedia-info";

interface StationEditPanelProps {
  station: Station;
  onSave: (updates: {
    name: string;
    geo: { lat: number; lng: number } | null;
    type: "rail" | "metro" | "light";
    importance: 1 | 2 | 3 | 4;
  }) => void;
  onDelete: () => void;
  onClose: () => void;
  isSaving: boolean;
}

export function StationEditPanel({
  station,
  onSave,
  onDelete,
  onClose,
  isSaving,
}: StationEditPanelProps) {
  const [name, setName] = useState(station.name);
  const [type, setType] = useState<"rail" | "metro" | "light">(station.type);
  const [importance, setImportance] = useState<1 | 2 | 3 | 4>(
    station.importance,
  );
  const [lat, setLat] = useState(station.geo?.lat?.toString() ?? "");
  const [lng, setLng] = useState(station.geo?.lng?.toString() ?? "");

  // Reset form when station changes
  useEffect(() => {
    setName(station.name);
    setType(station.type);
    setImportance(station.importance);
    setLat(station.geo?.lat?.toString() ?? "");
    setLng(station.geo?.lng?.toString() ?? "");
  }, [station]);

  const handleSave = () => {
    const parsedLat = parseFloat(lat);
    const parsedLng = parseFloat(lng);

    const geo =
      !isNaN(parsedLat) && !isNaN(parsedLng)
        ? { lat: parsedLat, lng: parsedLng }
        : null;

    onSave({ name, geo, type, importance });
  };

  const hasChanges =
    name !== station.name ||
    type !== station.type ||
    importance !== station.importance ||
    lat !== (station.geo?.lat?.toString() ?? "") ||
    lng !== (station.geo?.lng?.toString() ?? "");

  const handleLatPaste = (e: React.ClipboardEvent<HTMLInputElement>) => {
    const pasted = e.clipboardData.getData("text");
    const match = pasted.match(/^\s*(-?\d+\.?\d*)\s*,\s*(-?\d+\.?\d*)\s*$/);
    if (match && match[1] && match[2]) {
      e.preventDefault();
      setLat(match[1]);
      setLng(match[2]);
    }
  };

  return (
    <div className="rounded-lg border bg-card p-4 shadow-lg">
      <div className="mb-4 border-b pb-3">
        <div className="flex items-center justify-between">
          <h3 className="text-lg font-semibold">Edit Station</h3>
          <Button variant="ghost" size="icon-sm" onClick={onClose}>
            <XIcon className="size-4" />
          </Button>
        </div>
        <p className="mt-1 text-sm text-muted-foreground">
          ID: <span className="font-mono">{station.id}</span>
        </p>
      </div>

      <div className="flex flex-col gap-4">
        <div className="flex flex-col gap-1.5">
          <Label htmlFor="name">Name</Label>
          <p className="text-xs text-muted-foreground">
            Display name shown in the app
          </p>
          <Input
            id="name"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Station name"
          />
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="type">Type</Label>
            <Select
              value={type}
              onValueChange={(v) => setType(v as "rail" | "metro" | "light")}
            >
              <SelectTrigger id="type">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="rail">Rail</SelectItem>
                <SelectItem value="metro">Metro</SelectItem>
                <SelectItem value="light">Light</SelectItem>
              </SelectContent>
            </Select>
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="importance">Importance</Label>
            <Select
              value={String(importance)}
              onValueChange={(v) => setImportance(Number(v) as 1 | 2 | 3 | 4)}
            >
              <SelectTrigger id="importance">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="1">1 - Major</SelectItem>
                <SelectItem value="2">2 - Important</SelectItem>
                <SelectItem value="3">3 - Medium</SelectItem>
                <SelectItem value="4">4 - Minor</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        <div className="grid grid-cols-2 gap-3">
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="lat">Latitude</Label>
            <p className="text-xs text-muted-foreground">
              North-south position (-90 to 90)
            </p>
            <Input
              id="lat"
              type="number"
              step="0.000001"
              value={lat}
              onChange={(e) => setLat(e.target.value)}
              onPaste={handleLatPaste}
              placeholder="41.901"
            />
          </div>
          <div className="flex flex-col gap-1.5">
            <Label htmlFor="lng">Longitude</Label>
            <p className="text-xs text-muted-foreground">
              East-west position (-180 to 180)
            </p>
            <Input
              id="lng"
              type="number"
              step="0.000001"
              value={lng}
              onChange={(e) => setLng(e.target.value)}
              placeholder="12.501"
            />
          </div>
        </div>

        <div className="flex items-center gap-2 w-full border-t border-border pt-4">
          {lat && lng && (
            <a
              href={`https://www.google.com/maps?q=${lat},${lng}`}
              target="_blank"
              rel="noopener noreferrer"
              className={cn(
                buttonVariants({ variant: "outline", size: "sm" }),
                "flex-1",
              )}
            >
              <MapIcon className="size-4" />
              Google Maps
            </a>
          )}
          {station.id && (
            <a
              href={`https://iechub.rfi.it/ArriviPartenze/en/ArrivalsDepartures/Monitor?placeId=${station.id}&arrivals=False`}
              target="_blank"
              rel="noopener noreferrer"
              className={cn(
                buttonVariants({ variant: "outline", size: "sm" }),
                "flex-1",
              )}
            >
              <RadioTowerIcon className="size-4" />
              RFI Data
            </a>
          )}
        </div>

        <Collapsible defaultOpen className="border-t border-border pt-4">
          <CollapsibleTrigger className="flex w-full items-center justify-between text-sm font-medium">
            <span className="flex items-center gap-2">
              <BookOpenIcon className="size-4" />
              Wikipedia Info
            </span>
            <ChevronDownIcon className="size-4 transition-transform in-data-panel-open:rotate-180" />
          </CollapsibleTrigger>
          <CollapsibleContent>
            <WikipediaInfo
              stationName={station.name}
              currentCoordinates={
                lat && lng
                  ? { lat: parseFloat(lat), lng: parseFloat(lng) }
                  : null
              }
              onUseCoordinates={(wikiLat, wikiLng) => {
                setLat(wikiLat.toString());
                setLng(wikiLng.toString());
              }}
            />
          </CollapsibleContent>
        </Collapsible>

        <div className="flex gap-2 pt-2 border-t border-border">
          <Button
            onClick={handleSave}
            disabled={!name.trim() || isSaving || !hasChanges}
            className="flex-1"
          >
            <SaveIcon className="size-4" />
            {isSaving ? "Saving..." : "Save"}
          </Button>
          <Button variant="destructive" onClick={onDelete} disabled={isSaving}>
            <Trash2Icon className="size-4" />
            Delete
          </Button>
        </div>
      </div>
    </div>
  );
}

// apps/studio/src/lib/components/StationEditPanel.svelte
<script lang="ts">
    import type { Station } from "@repo/data";
    import {
        BookOpenIcon,
        ExternalLinkIcon,
        RadioTowerIcon,
        SaveIcon,
        Trash2Icon,
        XIcon,
    } from "@lucide/svelte";
    import WikipediaInfo from "$lib/components/WikipediaInfo.svelte";
    import { Button } from "$lib/components/ui/button";
    import { Input } from "$lib/components/ui/input";
    import { Label } from "$lib/components/ui/label";
    import { ScrollArea } from "$lib/components/ui/scroll-area";
    import * as Select from "$lib/components/ui/select";
    import { Separator } from "$lib/components/ui/separator";
    import { stationStore } from "$lib/stores/stations";

    let {
        station,
        isSaving,
        onSave,
        onDelete,
        onClose,
    }: {
        station: Station;
        isSaving: boolean;
        onSave: (updates: {
            name: string;
            geo: { lat: number; lng: number };
            type: "rail" | "metro" | "light";
            importance: 1 | 2 | 3 | 4;
        }) => void;
        onDelete: () => void;
        onClose: () => void;
    } = $props();

    let lastStationId = $state<string | null>(null);
    let name = $state("");
    let type = $state<"rail" | "metro" | "light">("rail");
    let importance = $state("4");
    let lat = $state("");
    let lng = $state("");

    $effect(() => {
        if (station.id === lastStationId) return;
        lastStationId = station.id;
        name = station.name;
        type = station.type;
        importance = station.importance.toString();
        lat = station.geo?.lat.toString() ?? "";
        lng = station.geo?.lng.toString() ?? "";
    });

    const hasChanges = $derived(
        name !== station.name ||
            type !== station.type ||
            Number(importance) !== station.importance ||
            lat !== (station.geo?.lat.toString() ?? "") ||
            lng !== (station.geo?.lng.toString() ?? ""),
    );

    function handleSave() {
        const parsedLat = parseFloat(lat);
        const parsedLng = parseFloat(lng);
        if (Number.isNaN(parsedLat) || Number.isNaN(parsedLng)) return;
        onSave({
            name,
            geo: { lat: parsedLat, lng: parsedLng },
            type,
            importance: Number(importance) as 1 | 2 | 3 | 4,
        });
    }

    const isItalianStation = $derived(/^IT[LM]?/.test(station.id));
    const railRadarBaseUrl = $derived(
        $stationStore.mode === "local"
            ? "http://localhost:3000"
            : "https://railradar24.com",
    );

    function handleLatPaste(event: ClipboardEvent) {
        const pasted = event.clipboardData?.getData("text") ?? "";
        const match = pasted.match(/^\s*(-?\d+\.?\d*)\s*,\s*(-?\d+\.?\d*)\s*$/);
        if (!match?.[1] || !match[2]) return;

        event.preventDefault();
        lat = match[1];
        lng = match[2];
    }
</script>

<aside
    class="flex h-full w-[24rem] shrink-0 flex-col border-l border-border bg-card text-card-foreground max-lg:w-88 max-md:absolute max-md:inset-y-0 max-md:right-0 max-md:z-20 max-md:max-w-[calc(100vw-2rem)]"
>
    <div class="border-b border-border px-4 py-3">
        <div class="flex items-center justify-between gap-3">
            <div class="min-w-0">
                <div
                    class="font-mono text-[10px] uppercase tracking-wider text-muted-foreground"
                >
                    Inspector
                </div>
                <h2 class="mt-1 truncate text-sm font-semibold">
                    {name || "Unnamed station"}
                </h2>
                <p
                    class="mt-0.5 truncate font-mono text-[11px] text-muted-foreground"
                >
                    {station.id}
                </p>
            </div>
            <Button
                variant="ghost"
                size="icon-sm"
                aria-label="Close"
                onclick={onClose}
            >
                <XIcon class="size-4" />
            </Button>
        </div>
    </div>

    <ScrollArea class="min-h-0 flex-1">
        <div class="flex flex-col gap-4 px-4 py-4">
            <div class="flex flex-col gap-1.5">
                <Label for="station-name">Name</Label>
                <p class="text-xs text-muted-foreground">
                    Display name shown in the app
                </p>
                <Input
                    id="station-name"
                    bind:value={name}
                    placeholder="Station name"
                />
            </div>

            <div class="grid grid-cols-2 gap-3">
                <div class="flex flex-col gap-1.5">
                    <Label>Type</Label>
                    <Select.Root type="single" bind:value={type}>
                        <Select.Trigger class="w-full">
                            {type === "rail"
                                ? "Rail"
                                : type === "metro"
                                  ? "Metro"
                                  : "Light"}
                        </Select.Trigger>
                        <Select.Content>
                            <Select.Item value="rail">Rail</Select.Item>
                            <Select.Item value="metro">Metro</Select.Item>
                            <Select.Item value="light">Light</Select.Item>
                        </Select.Content>
                    </Select.Root>
                </div>

                <div class="flex flex-col gap-1.5">
                    <Label>Importance</Label>
                    <Select.Root type="single" bind:value={importance}>
                        <Select.Trigger class="w-full">
                            {importance} - {importance === "1"
                                ? "Major"
                                : importance === "2"
                                  ? "Important"
                                  : importance === "3"
                                    ? "Medium"
                                    : "Minor"}
                        </Select.Trigger>
                        <Select.Content>
                            <Select.Item value="1">1 - Major</Select.Item>
                            <Select.Item value="2">2 - Important</Select.Item>
                            <Select.Item value="3">3 - Medium</Select.Item>
                            <Select.Item value="4">4 - Minor</Select.Item>
                        </Select.Content>
                    </Select.Root>
                </div>
            </div>

            <div class="grid grid-cols-2 gap-3">
                <div class="flex flex-col gap-1.5">
                    <Label for="station-lat">Latitude</Label>
                    <p class="text-xs text-muted-foreground">
                        North-south position
                    </p>
                    <Input
                        id="station-lat"
                        type="number"
                        step="0.000001"
                        bind:value={lat}
                        onpaste={handleLatPaste}
                    />
                </div>
                <div class="flex flex-col gap-1.5">
                    <Label for="station-lng">Longitude</Label>
                    <p class="text-xs text-muted-foreground">
                        East-west position
                    </p>
                    <Input
                        id="station-lng"
                        type="number"
                        step="0.000001"
                        bind:value={lng}
                    />
                </div>
            </div>

            <Separator />

            <div class="grid grid-cols-2 gap-2">
                {#if lat && lng}
                    <Button
                        variant="outline"
                        href={`https://www.google.com/maps?q=${lat},${lng}`}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <ExternalLinkIcon class="size-4" />
                        Google Maps
                    </Button>
                {/if}
                <Button
                    variant="outline"
                    href={`${railRadarBaseUrl}/station/${station.id}`}
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    <ExternalLinkIcon class="size-4" />
                    Rail Radar
                </Button>
                {#if isItalianStation}
                    <Button
                        variant="outline"
                        class={lat && lng ? "col-span-2" : ""}
                        href={`https://iechub.rfi.it/ArriviPartenze/en/ArrivalsDepartures/Monitor?placeId=${station.id}&arrivals=False`}
                        target="_blank"
                        rel="noopener noreferrer"
                    >
                        <RadioTowerIcon class="size-4" />
                        RFI Data
                    </Button>
                {/if}
            </div>

            <details class="border-t border-border pt-4" open>
                <summary
                    class="flex cursor-pointer items-center gap-2 text-sm font-medium"
                >
                    <BookOpenIcon class="size-4" />
                    Wikipedia Info
                </summary>
                <WikipediaInfo
                    stationName={station.name}
                    stationId={station.id}
                    currentCoordinates={lat && lng
                        ? { lat: parseFloat(lat), lng: parseFloat(lng) }
                        : null}
                    onUseCoordinates={(wikiLat, wikiLng) => {
                        lat = wikiLat.toString();
                        lng = wikiLng.toString();
                    }}
                />
            </details>
        </div>
    </ScrollArea>

    <div
        class="grid grid-cols-[1fr_auto] gap-2 border-t border-border bg-card px-4 py-3"
    >
        <Button
            disabled={!name.trim() || isSaving || !hasChanges}
            onclick={handleSave}
        >
            <SaveIcon class="size-4" />
            {isSaving ? "Saving..." : "Save"}
        </Button>
        <Button variant="destructive" disabled={isSaving} onclick={onDelete}>
            <Trash2Icon class="size-4" />
            Delete
        </Button>
    </div>
</aside>
