// apps/studio/app/components/wikipedia-info.tsx
"use client";

import {
  ExternalLinkIcon,
  BookOpenIcon,
  Loader2Icon,
  MapPinIcon,
} from "lucide-react";
import { Button, buttonVariants } from "@repo/ui/components/button";
import { cn } from "@repo/ui/lib/utils";
import { useWikipediaStation } from "../hooks/use-wikipedia-station";
import {
  getStationStatus,
  calculateDistance,
  formatDistance,
} from "../lib/wikipedia-parser";
import type { StationInfobox, StationStatus } from "../types/wikipedia";

interface WikipediaInfoProps {
  stationName: string;
  currentCoordinates?: { lat: number; lng: number } | null;
  onUseCoordinates?: (lat: number, lng: number) => void;
}

export function WikipediaInfo({
  stationName,
  currentCoordinates,
  onUseCoordinates,
}: WikipediaInfoProps) {
  const { data, isLoading, error } = useWikipediaStation(stationName);

  if (isLoading) {
    return (
      <div className="flex items-center gap-2 py-3 text-sm text-muted-foreground">
        <Loader2Icon className="size-4 animate-spin" />
        <span>Loading...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="py-3 text-sm text-muted-foreground">
        Failed to load Wikipedia data
      </div>
    );
  }

  if (!data) {
    const searchUrl = `https://it.wikipedia.org/w/index.php?search=${encodeURIComponent(`Stazione di ${stationName}`)}`;
    return (
      <div className="flex flex-col gap-2 py-2">
        <p className="text-sm text-muted-foreground">
          No Wikipedia article found
        </p>
        <a
          href={searchUrl}
          target="_blank"
          rel="noopener noreferrer"
          className={cn(
            buttonVariants({ variant: "outline", size: "sm" }),
            "w-full",
          )}
        >
          <BookOpenIcon className="size-4" />
          Search on Wikipedia
        </a>
      </div>
    );
  }

  return (
    <WikipediaContent
      data={data}
      currentCoordinates={currentCoordinates}
      onUseCoordinates={onUseCoordinates}
    />
  );
}

function WikipediaContent({
  data,
  currentCoordinates,
  onUseCoordinates,
}: {
  data: StationInfobox;
  currentCoordinates?: { lat: number; lng: number } | null;
  onUseCoordinates?: (lat: number, lng: number) => void;
}) {
  const status = getStationStatus(data.stato);

  // Calculate distance if both coordinates are available
  const distance =
    data.coordinates && currentCoordinates
      ? calculateDistance(
          currentCoordinates.lat,
          currentCoordinates.lng,
          data.coordinates.lat,
          data.coordinates.lng,
        )
      : null;

  return (
    <div className="flex flex-col gap-3 py-2">
      {/* Status badge */}
      {data.stato && <StatusBadge status={status} label={data.stato} />}

      {/* Coordinates */}
      {data.coordinates && (
        <div className="rounded-md border border-border bg-muted/50 p-3">
          <div className="flex items-center justify-between gap-2">
            <div className="flex items-center gap-2 text-sm">
              <MapPinIcon className="size-4 text-muted-foreground" />
              <span className="font-mono text-xs">
                {data.coordinates.lat.toFixed(6)},{" "}
                {data.coordinates.lng.toFixed(6)}
              </span>
            </div>
            {onUseCoordinates && (
              <Button
                variant="outline"
                size="sm"
                onClick={() =>
                  onUseCoordinates(data.coordinates!.lat, data.coordinates!.lng)
                }
              >
                Use
              </Button>
            )}
          </div>
          {distance !== null && (
            <div className="mt-2 text-xs text-muted-foreground">
              {distance < 1 ? (
                <span className="text-emerald-400">Coordinates match</span>
              ) : (
                <span>
                  Distance from current:{" "}
                  <span
                    className={cn(
                      "font-medium",
                      distance > 1000 ? "text-amber-400" : "text-foreground",
                    )}
                  >
                    {formatDistance(distance)}
                  </span>
                </span>
              )}
            </div>
          )}
        </div>
      )}

      {/* Wikipedia link */}
      {data.wikipediaUrl && (
        <a
          href={data.wikipediaUrl}
          target="_blank"
          rel="noopener noreferrer"
          className={cn(
            buttonVariants({ variant: "outline", size: "sm" }),
            "w-full",
          )}
        >
          <ExternalLinkIcon className="size-4" />
          View on Wikipedia
        </a>
      )}
    </div>
  );
}

function StatusBadge({
  status,
  label,
}: {
  status: StationStatus;
  label: string;
}) {
  const statusColors: Record<StationStatus, string> = {
    attiva: "bg-emerald-500/20 text-emerald-400 border-emerald-500/40",
    soppressa: "bg-red-500/20 text-red-400 border-red-500/40",
    chiusa: "bg-amber-500/20 text-amber-400 border-amber-500/40",
    unknown: "bg-zinc-500/20 text-zinc-400 border-zinc-500/40",
  };

  return (
    <span
      className={cn(
        "inline-flex w-fit items-center rounded-full border px-2.5 py-0.5 text-xs font-medium capitalize",
        statusColors[status],
      )}
    >
      {label}
    </span>
  );
}

// apps/studio/src/lib/components/WikipediaInfo.svelte
<script lang="ts">
  import { ExternalLinkIcon, MapPinIcon } from "@lucide/svelte";
  import { Badge } from "$lib/components/ui/badge";
  import { Button } from "$lib/components/ui/button";
  import type { StationInfobox, StationStatus } from "$lib/types/wikipedia";
  import { fetchWikipediaStation } from "$lib/wikipedia";
  import { calculateDistance, formatDistance, getStationStatus } from "$lib/wikipedia-parser";

  let {
    stationName,
    stationId = null,
    currentCoordinates = null,
    onUseCoordinates,
  }: {
    stationName: string;
    stationId?: string | null;
    currentCoordinates?: { lat: number; lng: number } | null;
    onUseCoordinates: (lat: number, lng: number) => void;
  } = $props();

  const COUNTRY_LANG: Record<string, string> = {
    IT: "it", DE: "de", CH: "de", AT: "de", FR: "fr", BE: "fr",
    NL: "nl", DK: "da", NO: "no", SE: "sv", FI: "fi", GB: "en", IE: "en",
  };
  const lang = $derived(
    stationId ? (COUNTRY_LANG[stationId.slice(0, 2).toUpperCase()] ?? "en") : "en",
  );

  let data = $state<StationInfobox | null>(null);
  let isLoading = $state(false);
  let error = $state<string | null>(null);

  async function load(name: string, id: string | null) {
    isLoading = true;
    error = null;
    try {
      data = await fetchWikipediaStation(name, id);
    } catch {
      error = "Failed to load Wikipedia data";
    } finally {
      isLoading = false;
    }
  }

  $effect(() => {
    if (stationName) void load(stationName, stationId);
  });

  function statusVariant(status: StationStatus): "default" | "secondary" | "destructive" | "outline" {
    if (status === "soppressa") return "destructive";
    if (status === "chiusa") return "outline";
    return "secondary";
  }
</script>

{#if isLoading}
  <div class="py-3 text-sm text-muted-foreground">Loading...</div>
{:else if error}
  <div class="py-3 text-sm text-muted-foreground">{error}</div>
{:else if !data}
  <div class="flex flex-col gap-2 py-2">
    <p class="text-sm text-muted-foreground">No Wikipedia article found</p>
    <Button
      variant="outline"
      class="w-full"
      target="_blank"
      rel="noopener noreferrer"
      href={`https://${lang}.wikipedia.org/w/index.php?search=${encodeURIComponent(stationName)}`}
    >
      Search on Wikipedia
    </Button>
  </div>
{:else}
  {@const status = getStationStatus(data.stato)}
  {@const distance = data.coordinates && currentCoordinates ? calculateDistance(currentCoordinates.lat, currentCoordinates.lng, data.coordinates.lat, data.coordinates.lng) : null}
  <div class="flex flex-col gap-3 py-2">
    {#if data.stato}
      <Badge variant={statusVariant(status)} class="w-fit capitalize">{data.stato}</Badge>
    {/if}

    {#if data.coordinates}
      <div class="rounded-md border border-border bg-muted/30 p-3">
        <div class="flex items-center justify-between gap-2">
          <div class="flex items-center gap-2">
            <MapPinIcon class="size-4 text-muted-foreground" />
            <span class="font-mono text-xs">
              {data.coordinates.lat.toFixed(6)}, {data.coordinates.lng.toFixed(6)}
            </span>
          </div>
          <Button variant="outline" size="sm" onclick={() => onUseCoordinates(data!.coordinates!.lat, data!.coordinates!.lng)}>
            Use
          </Button>
        </div>
        {#if distance !== null}
          <div class="mt-2 text-xs text-muted-foreground">
            {#if distance < 1}
              <span class="text-emerald-300">Coordinates match</span>
            {:else}
              Distance from current: <span class="font-medium text-foreground">{formatDistance(distance)}</span>
            {/if}
          </div>
        {/if}
      </div>
    {/if}

    {#if data.wikipediaUrl}
      <Button variant="outline" class="w-full" href={data.wikipediaUrl} target="_blank" rel="noopener noreferrer">
        <ExternalLinkIcon class="size-4" />
        View on Wikipedia
      </Button>
    {/if}
  </div>
{/if}
